### ISSUE TITLE
Creating fizsh files from ansible

### ISSUE THREAD

**Issue by kalsan** [zsh-users/fizsh#16]
Hi! I'm looking for a way to install fizsh from ansible. For this, I need a way to run fizsh from a script such that it creates the `.fizsh` directory with all contents.

How can this be achieved?

**Comment by guidovansteen** [comment]
Hi! You could temporarily add the command 'exit' to the file '~/.fizshrc' (like ~> 'echo exit >> ~/.fizsh/.fizshrc'). After that you could starts an interactive session by issuing the command 'fizsh'. This will populate the '~/.fizsh' directories. Due to the 'exit' command in the file ~/.fizsh/.fizshrc the interactive session would be terminated immediately. After that you should restore the original state of '~/.fizshrc', which might be achieved by 'head -n -1 ~/.fizsh/.fizshrc > ~/.fizsh/.fizshrc'.

**Comment by kalsan** [comment]
Works like a charm. Thanks a lot!
